name: Build and Deploy Worker Dreamer Docker Container

on:
  workflow_dispatch:

jobs:
  build-publish-worker-dreamer-docker:
    name: AI Horde Worker Dreamer Docker Container
    runs-on: ubuntu-latest
    steps:
    - name: "✔️ Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Free disk space
      uses: jlumbroso/free-disk-space@main
      with:
        android: true
        dotnet: true
        haskell: true
        tool-cache: false
        large-packages: false
        swap-storage: false
    - name: Build Dreamer Container
      run: docker build -t ghcr.io/db0/ai-horde-worker:${{ github.ref_name }}-dreamer -f docker/dreamer.Dockerfile .
    - name: Publish Dreamer Container
      run: docker push ghcr.io/db0/ai-horde-worker:${{ github.ref_name }}-dreamer
    - name: Inform with Discord Webhook
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: "New version of AI Horde Worker Dreamer Docker Container has been released: ghcr.io/db0/ai-horde-worker:${{ github.ref_name }}-dreamer"