name: Build and Deploy Worker Scribe Docker Container

on:
  workflow_dispatch:

jobs:
  build-publish-worker-scribe-docker:
    name: AI Horde Worker Scribe Docker Container
    runs-on: ubuntu-latest
    steps:
    - name: "✔️ Checkout"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Scribe Container
      run: docker build -t ghcr.io/db0/ai-horde-worker:${{ github.ref_name }}-scribe -f docker/scribe.Dockerfile .
    - name: Publish Scribe Container
      run: docker push ghcr.io/db0/ai-horde-worker:${{ github.ref_name }}-scribe
    - name: Inform with Discord Webhook
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        content: "New version of AI Horde Worker Scribe Docker Container has been released: ghcr.io/db0/ai-horde-worker:${{ github.ref_name }}-scribe"